---
output:  
    word_document :
        reference_docx: QaTableStyle6.docx
        toc: yes
---

```{r setup, include=FALSE}

options(scipen=999, digits = 5, width = 88)
options(qwraps2_markup = "markdown")

options(stringAsFactors = F)
options(dplyr.print_max = 10)
options(dplyr.pring_min = 5)

knitr::opts_chunk$set(#cache   = TRUE,
               echo    = FALSE,
               results = "hide",
               message = FALSE,
               warning = FALSE) 
startTime <- Sys.time()

library(knitr)
library(tidyverse)
library(qwraps2)


con <- DBI::dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server   = "cc-s-d05.ucdenver.pvt",
                      Database = "VDW_3_1_DH_0418")

```


```{r supporting_data_and_functions, include = FALSE}

start_dt <- "2011-01-01"
end_dt   <- "2016-12-31"

## helper functions
 # returns a vector with the column numbers of character variables in the data frame
charVars <- function(df) grep('^ch',sapply(df,class))

 # trims all character variables in a dataframe, sets blank to NA
trimChrVars <- function(df){
for(i in charVars(df)){
  df[,i] <- gsub('\\s+$','',df[,i])
  df[,i] <- ifelse(nchar(df[,i])==0,NA,df[,i])
}
  df
}

# age category calculator
ageCatCalc <- function(age){
  ageCat <- factor(
    ifelse(is.na(age)==TRUE, 0,
           ifelse(age<0              , 1, 
                  ifelse(age>=0 & age<2, 2,
                         ifelse(age>=2 & age<5, 3, 
                                ifelse(age>=5 & age<10, 4, 
                                       ifelse (age>=10 & age<15, 5, 
                                               ifelse(age>=15 & age<19, 6,
                                                      ifelse(age>=19 & age<22, 7,
                                                             ifelse(age>=22 & age<45, 8, 
                                                                    ifelse(age>=45 & age<65, 9, 
                                                                           ifelse(age>=65 & age<75, 10, 
                                                                                  ifelse(age>=75 & age<90, 11,
                                                                                         ifelse(age>=90 , 12, 13)))))) ))))))),
    levels=0:13,
    labels=c('Missing','Negative','0-1','2-4','5-9','10-14','15-18','19-21','22-44','45-64','65-74','75-89','90+','Other')
  )
  
  return(ageCat)
}

#Create long version of codes file

```

# Table Set 1: Facility Demographics

##Table 1A. Surgeries by Year and type of surgery

This table contains the number of procedures performed by year and type of procedure


```{r tab1_sum_stats}
          
tab1a <- odbc::dbGetQuery(con,
       "SELECT
       *
FROM
(
    SELECT
           CASE
               WHEN z.PX IN('0RG4070', '0RG4071', '0RG407J', '0RG40A0', '0RG40A1', '0RG40AJ', '0RG40J0', '0RG40J1', '0RG40JJ', '0RG40K0', '0RG40K1', '0RG40KJ', '0RG40Z0', '0RG40Z1', '0RG40ZJ', '0RG6070', '0RG6071', '0RG607J', '0RG60A0', '0RG60A1', '0RG60AJ', '0RG60J0', '0RG60J1', '0RG60JJ', '0RG60K0', '0RG60K1', '0RG60KJ', '0RG60Z0', '0RG60Z1', '0RG60ZJ', '0RG7070', '0RG7071', '0RG707J', '0RG70A0', '0RG70A1', '0RG70AJ', '0RG70J0', '0RG70J1', '0RG70JJ', '0RG70K0', '0RG70K1', '0RG70KJ', '0RG70Z0', '0RG70Z1', '0RG70ZJ', '0RG8070', '0RG8071', '0RG807J', '0RG80A0', '0RG80A1', '0RG80AJ', '0RG80J0', '0RG80J1', '0RG80JJ', '0RG80K0', '0RG80K1', '0RG80KJ', '0RG80Z0', '0RG80Z1', '0RG80ZJ', '0RGA070', '0RGA071', '0RGA07J', '0RGA0A0', '0RGA0A1', '0RGA0AJ', '0RGA0J0', '0RGA0J1', '0RGA0JJ', '0RGA0K0', '0RGA0K1', '0RGA0KJ', '0RGA0Z0', '0RGA0Z1', '0RGA0ZJ', '0SG0070', '0SG0071', '0SG007J', '0SG00A0', '0SG00A1', '0SG00AJ', '0SG00J0', '0SG00J1', '0SG00JJ', '0SG00K0', '0SG00K1', '0SG00KJ', '0SG00Z0', '0SG00Z1', '0SG00ZJ', '0SG1070', '0SG1071', '0SG107J', '0SG10A0', '0SG10A1', '0SG10AJ', '0SG10J0', '0SG10J1', '0SG10JJ', '0SG10K0', '0SG10K1', '0SG10KJ', '0SG10Z0', '0SG10Z1', '0SG10ZJ', '0SG3070', '0SG3071', '0SG307J', '0SG30A0', '0SG30A1', '0SG30AJ', '0SG30J0', '0SG30J1', '0SG30JJ', '0SG30K0', '0SG30K1', '0SG30KJ', '0SG30Z0', '0SG30Z1', '0SG30ZJ', '81', '81.01', '81.02', '81.03', '81.04', '81.05', '81.06', '81.07', '81.08', '81.09', '81.3', '81.35', '81.36', '81.37', '81.38', '81.39', '81.61', '81.62', '81.63', '81.64', '84.51', '22532', '22533', '22548', '22551', '22554', '22556', '22558', '22586', '22590', '22595', '22600', '22610', '22612', '22614', '22630', '22633', '22634', '22800', '22802', '22804', '22808', '22810', '22812', '22818', '22819', '22830', '22840', '22841', '22842', '22843', '22844', '22845', '22846', '22847', '22848', '22849', '22850', '22852', '22853', '22854', '22855', '22856', '22857', '22858', '22859', '22861', '22862', '22864', '22865', '22867', '22868', '22869', '22870')
               THEN 'spine'
               WHEN z.PX IN('0WU80JZ', '0WU84JZ', '34.74', '21740', '21742', '21743')
               THEN 'pectus'
           END AS ProcedureType,
      YEAR(z.ADATE) as px_date
    FROM
         DEMOGRAPHICS a
         JOIN [PROCEDURES] z
              ON z.PERSON_ID = a.PERSON_ID
    WHERE  z.ADATE >= '01/01/2011'
           AND DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0
                    END >= 10
           AND DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0
                    END <= 26
           AND 
               z.PX IN('0RG4070', '0RG4071', '0RG407J', '0RG40A0', '0RG40A1', '0RG40AJ', '0RG40J0', '0RG40J1', '0RG40JJ', '0RG40K0', '0RG40K1', '0RG40KJ', '0RG40Z0', '0RG40Z1', '0RG40ZJ', '0RG6070', '0RG6071', '0RG607J', '0RG60A0', '0RG60A1', '0RG60AJ', '0RG60J0', '0RG60J1', '0RG60JJ', '0RG60K0', '0RG60K1', '0RG60KJ', '0RG60Z0', '0RG60Z1', '0RG60ZJ', '0RG7070', '0RG7071', '0RG707J', '0RG70A0', '0RG70A1', '0RG70AJ', '0RG70J0', '0RG70J1', '0RG70JJ', '0RG70K0', '0RG70K1', '0RG70KJ', '0RG70Z0', '0RG70Z1', '0RG70ZJ', '0RG8070', '0RG8071', '0RG807J', '0RG80A0', '0RG80A1', '0RG80AJ', '0RG80J0', '0RG80J1', '0RG80JJ', '0RG80K0', '0RG80K1', '0RG80KJ', '0RG80Z0', '0RG80Z1', '0RG80ZJ', '0RGA070', '0RGA071', '0RGA07J', '0RGA0A0', '0RGA0A1', '0RGA0AJ', '0RGA0J0', '0RGA0J1', '0RGA0JJ', '0RGA0K0', '0RGA0K1', '0RGA0KJ', '0RGA0Z0', '0RGA0Z1', '0RGA0ZJ', '0SG0070', '0SG0071', '0SG007J', '0SG00A0', '0SG00A1', '0SG00AJ', '0SG00J0', '0SG00J1', '0SG00JJ', '0SG00K0', '0SG00K1', '0SG00KJ', '0SG00Z0', '0SG00Z1', '0SG00ZJ', '0SG1070', '0SG1071', '0SG107J', '0SG10A0', '0SG10A1', '0SG10AJ', '0SG10J0', '0SG10J1', '0SG10JJ', '0SG10K0', '0SG10K1', '0SG10KJ', '0SG10Z0', '0SG10Z1', '0SG10ZJ', '0SG3070', '0SG3071', '0SG307J', '0SG30A0', '0SG30A1', '0SG30AJ', '0SG30J0', '0SG30J1', '0SG30JJ', '0SG30K0', '0SG30K1', '0SG30KJ', '0SG30Z0', '0SG30Z1', '0SG30ZJ', '81', '81.01', '81.02', '81.03', '81.04', '81.05', '81.06', '81.07', '81.08', '81.09', '81.3', '81.35', '81.36', '81.37', '81.38', '81.39', '81.61', '81.62', '81.63', '81.64', '84.51', '0WU80JZ', '0WU84JZ', '34.74', '22532', '22533', '22548', '22551', '22554', '22556', '22558', '22586', '22590', '22595', '22600', '22610', '22612', '22614', '22630', '22633', '22634', '22800', '22802', '22804', '22808', '22810', '22812', '22818', '22819', '22830', '22840', '22841', '22842', '22843', '22844', '22845', '22846', '22847', '22848', '22849', '22850', '22852', '22853', '22854', '22855', '22856', '22857', '22858', '22859', '22861', '22862', '22864', '22865', '22867', '22868', '22869', '22870', '21740', '21742', '21743')
) AS P
PIVOT(COUNT(ProcedureType) FOR ProcedureType IN(
                                                       [spine],
                                                       [pectus])) AS PIV
ORDER BY px_date"
)

tab1a_tot <- odbc::dbGetQuery(con,
       "SELECT
      count(*) as n_pxs,
      YEAR(z.ADATE) as px_date
    FROM
         DEMOGRAPHICS a
         JOIN [PROCEDURES] z
              ON z.PERSON_ID = a.PERSON_ID
    WHERE  z.ADATE >= '01/01/2011'
           AND DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0
                    END >= 10
           AND DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0
                    END <= 26 
GROUP BY YEAR(z.ADATE)
ORDER BY YEAR(z.ADATE)"
)

tab1a_all <- tab1a %>% 
  left_join(tab1a_tot, by = "px_date") %>% 
  mutate(
    spine2  = paste0(spine, " (", round((spine/n_pxs) * 100, 2), "%)"),
    pectus2 = paste0(pectus, " (", round((pectus/n_pxs) * 100, 2), "%)")
  ) %>% 
  select(px_date, spine2, pectus2)

```

```{r tab1a_out, results="asis"}

knitr::kable(tab1a_all, col.names = c("Year", "Spine", "Pectus"))

```


# Table 1B:

#Table 1B: Cumulative Demographic Demographic Differences by Facility

```{r tab1b}

tab1b <- odbc::dbGetQuery(con,
       "SELECT
        DISTINCT(z.ENC_ID),
       CASE
               WHEN z.PX IN('0RG4070', '0RG4071', '0RG407J', '0RG40A0', '0RG40A1', '0RG40AJ', '0RG40J0', '0RG40J1', '0RG40JJ', '0RG40K0', '0RG40K1', '0RG40KJ', '0RG40Z0', '0RG40Z1', '0RG40ZJ', '0RG6070', '0RG6071', '0RG607J', '0RG60A0', '0RG60A1', '0RG60AJ', '0RG60J0', '0RG60J1', '0RG60JJ', '0RG60K0', '0RG60K1', '0RG60KJ', '0RG60Z0', '0RG60Z1', '0RG60ZJ', '0RG7070', '0RG7071', '0RG707J', '0RG70A0', '0RG70A1', '0RG70AJ', '0RG70J0', '0RG70J1', '0RG70JJ', '0RG70K0', '0RG70K1', '0RG70KJ', '0RG70Z0', '0RG70Z1', '0RG70ZJ', '0RG8070', '0RG8071', '0RG807J', '0RG80A0', '0RG80A1', '0RG80AJ', '0RG80J0', '0RG80J1', '0RG80JJ', '0RG80K0', '0RG80K1', '0RG80KJ', '0RG80Z0', '0RG80Z1', '0RG80ZJ', '0RGA070', '0RGA071', '0RGA07J', '0RGA0A0', '0RGA0A1', '0RGA0AJ', '0RGA0J0', '0RGA0J1', '0RGA0JJ', '0RGA0K0', '0RGA0K1', '0RGA0KJ', '0RGA0Z0', '0RGA0Z1', '0RGA0ZJ', '0SG0070', '0SG0071', '0SG007J', '0SG00A0', '0SG00A1', '0SG00AJ', '0SG00J0', '0SG00J1', '0SG00JJ', '0SG00K0', '0SG00K1', '0SG00KJ', '0SG00Z0', '0SG00Z1', '0SG00ZJ', '0SG1070', '0SG1071', '0SG107J', '0SG10A0', '0SG10A1', '0SG10AJ', '0SG10J0', '0SG10J1', '0SG10JJ', '0SG10K0', '0SG10K1', '0SG10KJ', '0SG10Z0', '0SG10Z1', '0SG10ZJ', '0SG3070', '0SG3071', '0SG307J', '0SG30A0', '0SG30A1', '0SG30AJ', '0SG30J0', '0SG30J1', '0SG30JJ', '0SG30K0', '0SG30K1', '0SG30KJ', '0SG30Z0', '0SG30Z1', '0SG30ZJ', '81', '81.01', '81.02', '81.03', '81.04', '81.05', '81.06', '81.07', '81.08', '81.09', '81.3', '81.35', '81.36', '81.37', '81.38', '81.39', '81.61', '81.62', '81.63', '81.64', '84.51', '22532', '22533', '22548', '22551', '22554', '22556', '22558', '22586', '22590', '22595', '22600', '22610', '22612', '22614', '22630', '22633', '22634', '22800', '22802', '22804', '22808', '22810', '22812', '22818', '22819', '22830', '22840', '22841', '22842', '22843', '22844', '22845', '22846', '22847', '22848', '22849', '22850', '22852', '22853', '22854', '22855', '22856', '22857', '22858', '22859', '22861', '22862', '22864', '22865', '22867', '22868', '22869', '22870')
               THEN 'spine'
               WHEN z.PX IN('0WU80JZ', '0WU84JZ', '34.74', '21740', '21742', '21743')
               THEN 'pectus'
           END AS ProcedureType,
      DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0 
                  END AS [AGE],
      a.GENDER,
      a.PRIMARY_LANGUAGE,
      a.RACE1, 
      b.HT,
      b.WT,
      c.GEOCODE
FROM
         DEMOGRAPHICS a
         INNER JOIN [PROCEDURES] z
              ON z.PERSON_ID = a.PERSON_ID
         LEFT JOIN [VITAL_SIGNS] b
              ON z.PERSON_ID = b.PERSON_ID
         LEFT JOIN [CENSUS_LOCATION] c
              ON z.PERSON_ID = c.PERSON_ID
    WHERE  z.ADATE >= '01/01/2011'
           AND DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0
                    END >= 10
           AND DATEDIFF(YY, a.BIRTH_DATE, z.ADATE) - CASE
                      WHEN DATEADD(YY, DATEDIFF(YY, a.BIRTH_DATE, z.ADATE), a.BIRTH_DATE) > z.ADATE
                      THEN 1
                      ELSE 0
                    END <= 26
           AND 
               z.PX IN('0RG4070', '0RG4071', '0RG407J', '0RG40A0', '0RG40A1', '0RG40AJ', '0RG40J0', '0RG40J1', '0RG40JJ', '0RG40K0', '0RG40K1', '0RG40KJ', '0RG40Z0', '0RG40Z1', '0RG40ZJ', '0RG6070', '0RG6071', '0RG607J', '0RG60A0', '0RG60A1', '0RG60AJ', '0RG60J0', '0RG60J1', '0RG60JJ', '0RG60K0', '0RG60K1', '0RG60KJ', '0RG60Z0', '0RG60Z1', '0RG60ZJ', '0RG7070', '0RG7071', '0RG707J', '0RG70A0', '0RG70A1', '0RG70AJ', '0RG70J0', '0RG70J1', '0RG70JJ', '0RG70K0', '0RG70K1', '0RG70KJ', '0RG70Z0', '0RG70Z1', '0RG70ZJ', '0RG8070', '0RG8071', '0RG807J', '0RG80A0', '0RG80A1', '0RG80AJ', '0RG80J0', '0RG80J1', '0RG80JJ', '0RG80K0', '0RG80K1', '0RG80KJ', '0RG80Z0', '0RG80Z1', '0RG80ZJ', '0RGA070', '0RGA071', '0RGA07J', '0RGA0A0', '0RGA0A1', '0RGA0AJ', '0RGA0J0', '0RGA0J1', '0RGA0JJ', '0RGA0K0', '0RGA0K1', '0RGA0KJ', '0RGA0Z0', '0RGA0Z1', '0RGA0ZJ', '0SG0070', '0SG0071', '0SG007J', '0SG00A0', '0SG00A1', '0SG00AJ', '0SG00J0', '0SG00J1', '0SG00JJ', '0SG00K0', '0SG00K1', '0SG00KJ', '0SG00Z0', '0SG00Z1', '0SG00ZJ', '0SG1070', '0SG1071', '0SG107J', '0SG10A0', '0SG10A1', '0SG10AJ', '0SG10J0', '0SG10J1', '0SG10JJ', '0SG10K0', '0SG10K1', '0SG10KJ', '0SG10Z0', '0SG10Z1', '0SG10ZJ', '0SG3070', '0SG3071', '0SG307J', '0SG30A0', '0SG30A1', '0SG30AJ', '0SG30J0', '0SG30J1', '0SG30JJ', '0SG30K0', '0SG30K1', '0SG30KJ', '0SG30Z0', '0SG30Z1', '0SG30ZJ', '81', '81.01', '81.02', '81.03', '81.04', '81.05', '81.06', '81.07', '81.08', '81.09', '81.3', '81.35', '81.36', '81.37', '81.38', '81.39', '81.61', '81.62', '81.63', '81.64', '84.51', '0WU80JZ', '0WU84JZ', '34.74', '22532', '22533', '22548', '22551', '22554', '22556', '22558', '22586', '22590', '22595', '22600', '22610', '22612', '22614', '22630', '22633', '22634', '22800', '22802', '22804', '22808', '22810', '22812', '22818', '22819', '22830', '22840', '22841', '22842', '22843', '22844', '22845', '22846', '22847', '22848', '22849', '22850', '22852', '22853', '22854', '22855', '22856', '22857', '22858', '22859', '22861', '22862', '22864', '22865', '22867', '22868', '22869', '22870', '21740', '21742', '21743')"
)

tab1b$stateFP <- ifelse(tab1b$GEOCODE == "", NA, substr(tab1b$GEOCODE, 1, 2)) 

states <- chordsTables::stateCnty %>% 
  select(state, stateFP) %>% 
  filter(!duplicated(stateFP))

tab1b2 <- tab1b %>% 
  left_join(., states, by = "stateFP")
  

tab1b_sum <- 
    list("Age" =
       list("Mean (SD)" = ~ qwraps2::mean_sd(AGE, na_rm = T),
            "Median (IQR)"    = ~ qwraps2::median_iqr(AGE, na_rm = T)),
       "Gender (Freqency(%))" =
       list("Male" = ~ qwraps2::n_perc(GENDER == "M", na_rm = T)),
       "Primary Language (Freqency(%))" =
       list("English" = ~ qwraps2::n_perc(PRIMARY_LANGUAGE == "eng", na_rm = T),
            "Spanish" = ~ qwraps2::n_perc(PRIMARY_LANGUAGE == "spa", na_rm = T)),
       "Race (Freqency(%))" =
       list("Native Hawaiian or Other Pacific Islander"   = ~ qwraps2::n_perc(RACE1 == "HP", na_rm = T),
            "American Indian/Alaska Native"               = ~ qwraps2::n_perc(RACE1 == "IN", na_rm = T),
            "Asian"                                       = ~ qwraps2::n_perc(RACE1 == "AS", na_rm = T),
            "Black or African American"                   = ~ qwraps2::n_perc(RACE1 == "BA", na_rm = T),
            "White"                                       = ~ qwraps2::n_perc(RACE1 == "WH", na_rm = T),
            "More than one race"                          = ~ qwraps2::n_perc(RACE1 == "MU", na_rm = T),
            "Unknown"                                     = ~ qwraps2::n_perc(RACE1 == "UN", na_rm = T)),
       "Height" =
       list("Mean (SD)" = ~ qwraps2::mean_sd(HT, na_rm = T)),
       "Weight" = 
       list("Mean (SD)" = ~ qwraps2::mean_sd(WT, na_rm = T)),
       "State of patient address" = 
         list("Colorado"     = ~ qwraps2::n_perc(state == "CO", na_rm = T),
              "Wyoming"      = ~ qwraps2::n_perc(state == "WY", na_rm = T),
              "Nebraska"     = ~ qwraps2::n_perc(state == "NE", na_rm = T),
              "New Mexico"   = ~ qwraps2::n_perc(state == "NM", na_rm = T),
              "Oklahoma"     = ~ qwraps2::n_perc(state == "OK", na_rm = T),
              "South Dakota" = ~ qwraps2::n_perc(state == "SD", na_rm = T),
              "Kansas"       = ~ qwraps2::n_perc(state == "KS", na_rm = T),
              "Other"        = ~ qwraps2::n_perc(!(state %in% c("CO", "WY", "NE", "NM", "OK", "SD", "KS")) , 
                                                 na_rm = T))
)


```

```{r tab1b_disp, results="asis"}

if(length(dimnames(table(tab1b2$ProcedureType))) == 1){
  tab1b_tot_sum <- qwraps2::summary_table(tab1b2, tab1b_sum)
  tab1b_out <- tab1b_tot_sum
  print(tab1b_out, cnames = dimnames(table(tab1b2$ProcedureType))[[1]][1])
} else{
  tab1b_tot_sum <- qwraps2::summary_table(tab1b2, tab1b_sum)
  tab1b_proc_sum <- qwraps2::summary_table(dplyr::group_by(tab1b2, "ProcedureType"), tab1b_sum)
  tab1b_out <- cbind(tab1b_tot_sum, tab1b_proc_sum)
  print(tab1b_out, cnames = c("Total", dimnames(table(tab1b2$ProcedureType))[[1]]))
} 

```
